# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_buffering', '0002_auto_20160815_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureangle',
            name='small_picture_path',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
