# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_buffering', '0003_furnitureangle_small_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegangle',
            name='small_picture_path',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
